# Generated by Django 4.1 on 2022-11-07 21:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server_api.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wallet_address",
                    models.CharField(
                        max_length=42,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                42, "Address incorrect"
                            )
                        ],
                    ),
                ),
                (
                    "user_email",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "([\\w]+[.s-]{0,1})+@[A-Za-z]*(.com)",
                                "Email not correct!",
                            )
                        ],
                    ),
                ),
                ("user_name", models.CharField(max_length=200, unique=True)),
                (
                    "password",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                6, "Password should be a minimum of 6 characters"
                            ),
                            server_api.validators.PasswordValidator,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("avatar", models.IntegerField(default=0)),
                ("reset_requested", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=32,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                12, "Invalid Length!"
                            )
                        ],
                    ),
                ),
                ("expiry", models.FloatField(default=1667857322.1728609)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                6, "Invalid Token!"
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chips_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(
                                6, "Invalid Length!"
                            )
                        ]
                    ),
                ),
                ("expiry", models.IntegerField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_api.user",
                    ),
                ),
            ],
        ),
    ]
