# Generated by Django 4.1 on 2022-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="expiry",
            field=models.FloatField(default=1667857344.461052),
        ),
    ]
