# Generated by Django 4.0.4 on 2022-06-28 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42, 'Address incorrect')])),
                ('user_email', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('([\\w]+[.-]{0,1})+@[A-Za-z]*(.com)', 'Email not correct!')])),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(validators=[django.core.validators.MinLengthValidator(6, 'Invalid Length!')])),
                ('expiry', models.IntegerField(null=True)),
                ('hello', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server_api.user')),
            ],
        ),
    ]
