# Generated by Django 4.0.4 on 2022-06-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='hello',
        ),
    ]
