# Generated by Django 4.0.4 on 2022-08-26 11:13

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import server_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0004_alter_user_user_email_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, validators=[django.core.validators.MinLengthValidator(6, 'Password should be a minimum of 6 characters'), server_api.validators.PasswordValidator]),
            preserve_default=False,
        ),
    ]
