# Generated by Django 4.1 on 2022-08-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0006_alter_session_expiry_alter_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.IntegerField(default=1661636779.560809),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server_api.user')),
            ],
        ),
    ]
