# Generated by Django 4.1 on 2022-08-28 00:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0007_alter_session_expiry_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelsCleared', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.IntegerField(default=1661645791.4251451),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('([\\w]+[.s-]{0,1})+@[A-Za-z]*(.com)', 'Email not correct!')]),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server_api.user'),
        ),
    ]
