# Generated by Django 4.1 on 2022-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0008_progress_alter_session_expiry_alter_user_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.IntegerField(default=1662916032.9626272),
        ),
    ]
