# Generated by Django 4.1 on 2022-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_api', '0009_alter_session_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expiry',
            field=models.FloatField(default=1662916595.864203),
        ),
    ]
