# Generated by Django 4.1 on 2022-10-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server_api", "0011_alter_session_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chips_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_api.user",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="session",
            name="expiry",
            field=models.FloatField(default=1666941213.419596),
        ),
        migrations.DeleteModel(name="Progress",),
    ]
