# Generated by Django 4.1 on 2022-10-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_api", "0012_chips_alter_session_expiry_delete_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="avatar", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="session",
            name="expiry",
            field=models.FloatField(default=1666944000.117764),
        ),
    ]
