# Generated by Django 4.1 on 2022-10-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_api", "0013_user_avatar_alter_session_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="expiry",
            field=models.FloatField(default=1666946940.3217258),
        ),
    ]
