# Generated by Django 4.1 on 2022-10-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_api", "0015_alter_session_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="expiry",
            field=models.FloatField(default=1667067905.415935),
        ),
    ]
